export const defaultContent = {
  brandName: "Citi Cabana",
  navRooms: "Rooms",
  navEvents: "Events",
  navGallery: "Gallery",
  navBook: "Book Now",
  menuToggle: "Toggle menu",
  closeBookingLabel: "Close booking window",
  closeGalleryLabel: "Close gallery",
  closeLightboxLabel: "Close image",
  previousImageLabel: "Previous image",
  nextImageLabel: "Next image",
  heroTitle: "Citi Cabana",
  heroTagline: "Your fun and peaceful escape from the everyday rush.",
  heroImage: "/images/hero.jpg",
  barCheckin: "Check-in",
  barCheckout: "Check-out",
  barGuests: "Guests",
  barAvailability: "Check Availability",
  roomsTitle: "Stay With Us",
  roomsSubtitle: "Discover good vibes and tropical feels.",
  roomAmenitiesNote:
    "Guests also have full access to general resort amenities including our swimming pool, parking, and food service options.",
  roomCapacityLabel: "Capacity:",
  roomInclusionsLabel: "Inclusions:",
  roomNightLabel: "/ night",
  bookThisStay: "Book This Stay",
  eventsTitle: "Celebrate Here",
  eventsDescription:
    "Host your weddings, baptisms, birthdays, and special occasions in our beautiful event spaces. We offer customized setups tailored to unforgettable moments.",
  eventsImage: "/images/events.jpg",
  eventsButton: "Inquire About Events",
  galleryTitle: "The Experience",
  galleryButton: "View Full Gallery",
  galleryModalTitle: "Full Gallery",
  pageTitle: "Citi Cabana Farm House Inn",
  pageDescription:
    "Your fun and peaceful escape from the everyday rush. Discover good vibes, tropical feels, and unforgettable moments!",
  address: "Zone 1, Peter Jay Dunca Street\nSan Isidro, Tarlac City",
  landmark: "Landmark: 7-Eleven San Isidro, after the San Isidro Bridge",
  facebookLabel: "Follow on Facebook",
  facebookUrl: "https://www.facebook.com/share/1Ge1EiLjvU/?mibextid=wwXIfr",
  contactTitle: "Contact",
  phonePrimary: "0912-785-5801",
  phoneSecondary: "0907-754-8567",
  contactEmail: "citicabana31@gmail.com",
  policiesTitle: "Policies",
  checkinPolicy: "Check-in: 2:00 PM | Check-out: 12:00 NN",
  downpaymentPolicy: "50% downpayment required to confirm",
  paymentPolicy: "Cash, GCash, Bank transfer accepted",
  bookingTabRoom: "Book a Room",
  bookingTabEvent: "Book an Event",
  roomSuccessTitle: "Thank you!",
  roomSuccessText:
    "Your request is pending confirmation. Our staff will contact you shortly.",
  roomAnotherRequest: "Submit another request",
  stayStepTitle: "1. Your Stay",
  checkinLabel: "Check-in *",
  checkoutLabel: "Check-out *",
  dateError: "Check-out must be after check-in.",
  roomTypeLabel: "Room Type *",
  roomTypePlaceholder: "Select a room...",
  guestsLabel: "Guests *",
  detailsStepTitle: "2. Your Details",
  fullNameLabel: "Full Name *",
  contactLabel: "Contact Number *",
  notesLabel: "Notes (Optional)",
  roomSubmit: "Submit Reservation Request",
  eventSuccessTitle: "Thank you!",
  eventSuccessText:
    "Your event inquiry has been received. We will contact you to discuss details and pricing.",
  eventAnotherRequest: "Submit another request",
  eventStepTitle: "1. Event Details",
  eventTypeLabel: "Event Type *",
  eventDateLabel: "Date *",
  eventGuestsLabel: "Expected Guests *",
  eventTimeLabel: "Time Block *",
  eventDetailsTitle: "2. Your Details",
  eventNotesLabel: "Event Notes (Optional)",
  eventSubmit: "Inquire Now",
  summaryTitle: "Summary",
  summaryRoomLabel: "Room:",
  summaryDatesLabel: "Dates:",
  summaryNightsLabel: "Nights:",
  summaryTotalLabel: "Estimated Total:",
  summaryDownpayment: "50% downpayment required upon confirmation.",
  eventPlaceholder: "Event Space",
  eventPricingText:
    "Event pricing is customized based on requirements and package inclusions.",
  eventQuoteText:
    "Submit your inquiry and our events team will provide a comprehensive quote.",
  optionSelect: "Select...",
  eventOptionWedding: "Wedding",
  eventOptionBirthday: "Birthday",
  eventOptionBaptism: "Baptism",
  eventOptionOther: "Other",
  timeOptionMorning: "Morning",
  timeOptionAfternoon: "Afternoon",
  timeOptionEvening: "Evening",
  timeOptionFullDay: "Full Day",
  roomSummaryEmpty: "Select a room",
  roomSummaryNotSelected: "Not selected",
  invalidDates: "Invalid dates",
  galleryImageAlt: "Citi Cabana gallery photo",
};

export const defaultRooms = [
  {
    id: "standard",
    name: "Standard Room",
    capacity: "2 pax (double bed)",
    rate: 1000,
    inventory: 5,
    image: "/images/room-standard.jpg",
  },
  {
    id: "twin",
    name: "Twin Room",
    capacity: "2-4 pax (2 separate beds)",
    rate: 1500,
    inclusions: "Aircon, TV, private bathroom",
    inventory: 1,
    image: "/images/room-twin.jpg",
  },
  {
    id: "couple",
    name: "Couple Room",
    capacity: "2 pax (queen bed)",
    rate: 1500,
    inclusions: "Aircon, TV, private bathroom",
    inventory: 4,
    image: "/images/room-couple.jpg",
  },
  {
    id: "family",
    name: "Family Room",
    capacity: "4-6 pax (2 double beds)",
    rate: 2300,
    inclusions: "Aircon, TV, private bathroom",
    inventory: 2,
    image: "/images/room-family.jpg",
  },
  {
    id: "villa",
    name: "Villa (private pool)",
    capacity: "10 pax",
    rate: 9000,
    inclusions: "Aircon, TV, private bathroom, private pool",
    inventory: 1,
    image: "/images/room-villa.jpg",
  },
];

export const defaultGallery = [
  "/images/gallery-01.jpg",
  "/images/gallery-02.jpg",
  "/images/gallery-03.jpg",
  "/images/gallery-04.jpg",
  "/images/gallery-05.jpg",
  "/images/hero.jpg",
  "/images/room-standard.jpg",
  "/images/events.jpg",
];
